### ISSUE TITLE
Parallel

### ISSUE THREAD

**Issue by reganbaucke** [reganbaucke/JuDGE.jl#17]
Currently no support for parallel processing of sub problems. Use this thread as a discussion for what this feature (and its interface) might look like.

**Comment by adow031** [comment]
Gurobi's MIP solver is already multi-threaded. Instead of solving sub-problems in parallel I've added partial pricing, using the column_subset keyword for solve. However, it may be useful to have an adaptive bound-gap / time-limit for sub-problem MIPs (and the required changes to lower-bound calculations).
