### ISSUE TITLE
Non-active shutdown variables are not binary when written to file

### ISSUE THREAD

**Issue by calroughan** [reganbaucke/JuDGE.jl#26]
Shutdown variables that are supposed to be off, are fractional in the write_solution_to_file()  and print.expansions() function calls. 

![image](https://user-images.githubusercontent.com/61723840/96356300-f0c9b300-1148-11eb-8548-5a415ac054d1.png)

**Comment by adow031** [comment]
Gurobi has a default integer tolerance of 10e-8. JuDGE's default is something similar.

For some of the output functions written to the console we preprocess the values so it's clear what investments are set. However, this shouldn't be done in the full output, since the user should be able to analyze the true solution.
